services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/static
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  staticfiles:
